# Streamlit configuration file

[server]
port = 8501
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
textColor = "#262730"

[logger]
level = "info"